version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todolist-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todolist-network

volumes:
  postgres-data:

networks:
  todolist-network:
